export const CONSTANT = {
  LANGUAGES: {
    VI: "vi-VN",
    EN: "en-US",
    JA: "ja-JP",
    CN: "zh-CN",
    TW: "zh-TW",
  },
  TOKEN_STORAGE_KEY: {
    ACCESS_TOKEN: "access_token",
    REFRESH_TOKEN: "refresh_token",
    TOKEN_TYPE: "token_type",
    EXPRIES_IN: "expires_in",
    EXPRIES_AT: "expires_at",
    CURRENCY: "currency",
    WEBSITE_SHOPPING: "websiteShopping",
    FIRST_LAUNCH_APP: "first_launch_app",
    LANGUAGE: "language",
    ANONYMOUS_ID: "ANONYMOUS_ID",
    PRIMARY_CURRENCY: "PRIMARY_CURRENCY",
    REMEMBER_USER: "remember_user",
    REVOKE_TOKEN_ENDPOINT: "revocation",
  },
  ICON_TYPE: {
    AntDesign: "AntDesign",
    Entypo: "Entypo",
    EvilIcons: "EvilIcons",
    Fontisto: "Fontisto",
    Feather: "Feather",
    FontAwesome: "FontAwesome",
    Foundation: "Foundation",
    Ionicons: "Ionicons",
    MaterialIcons: "MaterialIcons",
    MaterialCommunityIcons: "MaterialCommunityIcons",
    Octicons: "Octicons",
    Zocial: "Zocial",
    SimpleLineIcons: "SimpleLineIcons",
    FontAwesome5: "FontAwesome5",
  },
  ERROR_CODE: {
    ERROR_SERVER: "errorServer",
  },
};
